CREATE TABLE roles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(50) UNIQUE NOT NULL,
    description VARCHAR(200),
    permissions JSON,
    is_active BOOLEAN DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email VARCHAR(120) UNIQUE NOT NULL,
    username VARCHAR(80) UNIQUE NOT NULL,
    password_hash VARCHAR(256) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone VARCHAR(20),
    profile_picture VARCHAR(200),
    is_active BOOLEAN DEFAULT 1,
    is_verified BOOLEAN DEFAULT 0,
    is_approved BOOLEAN DEFAULT 0,
    is_system_admin BOOLEAN DEFAULT 0,
    last_login DATETIME,
    role_id INTEGER,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (role_id) REFERENCES roles(id)
);
CREATE TABLE branches (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(20) UNIQUE NOT NULL,
    address VARCHAR(200),
    city VARCHAR(50),
    state VARCHAR(50),
    country VARCHAR(50),
    postal_code VARCHAR(20),
    phone VARCHAR(20),
    email VARCHAR(120),
    manager_name VARCHAR(100),
    opening_time TIME,
    closing_time TIME,
    days_open JSON,
    is_active BOOLEAN DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE customers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER UNIQUE,
    date_of_birth DATE,
    gender VARCHAR(20),
    address VARCHAR(200),
    city VARCHAR(50),
    state VARCHAR(50),
    country VARCHAR(50),
    postal_code VARCHAR(20),
    preferences JSON,
    total_spent FLOAT DEFAULT 0.0,
    total_visits INTEGER DEFAULT 0,
    is_walk_in BOOLEAN DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE TABLE managers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER UNIQUE,
    branch_id INTEGER,
    employee_id VARCHAR(50) UNIQUE,
    hire_date DATE,
    salary FLOAT,
    emergency_contact VARCHAR(20),
    emergency_contact_name VARCHAR(100),
    is_active BOOLEAN DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (branch_id) REFERENCES branches(id)
);
CREATE TABLE receptionists (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER UNIQUE,
    branch_id INTEGER,
    employee_id VARCHAR(50) UNIQUE,
    hire_date DATE,
    salary FLOAT,
    is_active BOOLEAN DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (branch_id) REFERENCES branches(id)
);
CREATE TABLE stylists (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER UNIQUE,
    branch_id INTEGER,
    employee_id VARCHAR(50) UNIQUE,
    specialization VARCHAR(200),
    experience_years INTEGER DEFAULT 0,
    skills JSON,
    certification VARCHAR(200),
    hire_date DATE,
    salary FLOAT,
    commission_rate FLOAT DEFAULT 0.0,
    rating FLOAT DEFAULT 0.0,
    is_available BOOLEAN DEFAULT 1,
    is_active BOOLEAN DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (branch_id) REFERENCES branches(id)
);
CREATE TABLE finances (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER UNIQUE,
    branch_id INTEGER,
    employee_id VARCHAR(50) UNIQUE,
    hire_date DATE,
    salary FLOAT,
    is_active BOOLEAN DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (branch_id) REFERENCES branches(id)
);
CREATE TABLE inventories (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER UNIQUE,
    branch_id INTEGER,
    employee_id VARCHAR(50) UNIQUE,
    hire_date DATE,
    salary FLOAT,
    is_active BOOLEAN DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (branch_id) REFERENCES branches(id)
);
CREATE TABLE categories (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(200),
    icon VARCHAR(50),
    image VARCHAR(200),
    parent_id INTEGER,
    is_active BOOLEAN DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (parent_id) REFERENCES categories(id)
);
CREATE TABLE services (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    price FLOAT NOT NULL,
    duration_minutes INTEGER NOT NULL,
    category_id INTEGER,
    branch_id INTEGER,
    image VARCHAR(200),
    is_active BOOLEAN DEFAULT 1,
    is_popular BOOLEAN DEFAULT 0,
    discount_percentage FLOAT DEFAULT 0.0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES categories(id),
    FOREIGN KEY (branch_id) REFERENCES branches(id)
);
CREATE TABLE promotions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    code VARCHAR(50) UNIQUE,
    discount_type VARCHAR(20),
    discount_value FLOAT NOT NULL,
    start_date DATETIME NOT NULL,
    end_date DATETIME NOT NULL,
    min_spend FLOAT DEFAULT 0.0,
    max_discount FLOAT,
    usage_limit INTEGER,
    usage_count INTEGER DEFAULT 0,
    per_user_limit INTEGER DEFAULT 1,
    applicable_to VARCHAR(20) DEFAULT 'all',
    is_active BOOLEAN DEFAULT 1,
    is_public BOOLEAN DEFAULT 1,
    image VARCHAR(200),
    terms TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE service_promotions (
    service_id INTEGER,
    promotion_id INTEGER,
    PRIMARY KEY (service_id, promotion_id),
    FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE CASCADE,
    FOREIGN KEY (promotion_id) REFERENCES promotions(id) ON DELETE CASCADE
);
CREATE TABLE appointments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    customer_id INTEGER NOT NULL,
    service_id INTEGER NOT NULL,
    stylist_id INTEGER,
    branch_id INTEGER NOT NULL,
    receptionist_id INTEGER,
    appointment_date DATE NOT NULL,
    appointment_time TIME NOT NULL,
    end_time TIME,
    status VARCHAR(20) DEFAULT 'pending',
    notes TEXT,
    customer_notes TEXT,
    stylist_notes TEXT,
    is_walk_in BOOLEAN DEFAULT 0,
    is_rescheduled BOOLEAN DEFAULT 0,
    rescheduled_from INTEGER,
    check_in_time DATETIME,
    start_time DATETIME,
    completion_time DATETIME,
    total_amount FLOAT NOT NULL,
    discount_amount FLOAT DEFAULT 0.0,
    final_amount FLOAT NOT NULL,
    before_photos JSON,
    after_photos JSON,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, duration INTEGER DEFAULT 60, price FLOAT, paid BOOLEAN DEFAULT 0,
    FOREIGN KEY (customer_id) REFERENCES customers(id),
    FOREIGN KEY (service_id) REFERENCES services(id),
    FOREIGN KEY (stylist_id) REFERENCES stylists(id),
    FOREIGN KEY (branch_id) REFERENCES branches(id),
    FOREIGN KEY (receptionist_id) REFERENCES receptionists(id)
);
CREATE TABLE payments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    appointment_id INTEGER NOT NULL,
    customer_id INTEGER NOT NULL,
    amount FLOAT NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    payment_status VARCHAR(20) DEFAULT 'pending',
    transaction_id VARCHAR(100),
    reference_number VARCHAR(50) UNIQUE,
    payment_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    verified_at DATETIME,
    verified_by INTEGER,
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, receipt_number VARCHAR(50), branch_id INTEGER REFERENCES branches(id),
    FOREIGN KEY (appointment_id) REFERENCES appointments(id),
    FOREIGN KEY (customer_id) REFERENCES customers(id),
    FOREIGN KEY (verified_by) REFERENCES finances(id)
);
CREATE TABLE receipts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    appointment_id INTEGER NOT NULL,
    payment_id INTEGER NOT NULL,
    customer_id INTEGER NOT NULL,
    receipt_number VARCHAR(50) UNIQUE NOT NULL,
    receipt_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    subtotal FLOAT NOT NULL,
    tax FLOAT DEFAULT 0.0,
    discount FLOAT DEFAULT 0.0,
    total FLOAT NOT NULL,
    payment_method VARCHAR(50),
    transaction_id VARCHAR(100),
    items JSON,
    customer_details JSON,
    business_details JSON,
    pdf_path VARCHAR(200),
    is_printed BOOLEAN DEFAULT 0,
    is_emailed BOOLEAN DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, invoice_number VARCHAR(50), customer_name VARCHAR(100), customer_phone VARCHAR(20), customer_email VARCHAR(100), customer_id_number VARCHAR(50), transaction_code VARCHAR(100), amount_paid FLOAT, tax_rate FLOAT DEFAULT 0.16, service_items JSON, points_earned INTEGER DEFAULT 0, points_balance INTEGER DEFAULT 0, status VARCHAR(20) DEFAULT 'generated', sent_at DATETIME, sent_via VARCHAR(20), printed_at DATETIME, downloaded_at DATETIME, branch_name VARCHAR(100), branch_address VARCHAR(200), branch_phone VARCHAR(20), branch_email VARCHAR(100), branch_website VARCHAR(100), stylist_name VARCHAR(100), receptionist_name VARCHAR(100), finance_officer VARCHAR(100), signature_customer VARCHAR(255), signature_receptionist VARCHAR(255), signature_authorized VARCHAR(255), notes TEXT, logo_path VARCHAR(500), logo_url VARCHAR(500), business_logo VARCHAR(500), company_name VARCHAR(100), company_address VARCHAR(200), company_phone VARCHAR(20), company_email VARCHAR(100), company_website VARCHAR(100), header_image VARCHAR(500), footer_image VARCHAR(500), signature_image VARCHAR(500), company_logo VARCHAR(500), receipt_background VARCHAR(500), watermark_image VARCHAR(500), image_style VARCHAR(50) DEFAULT 'default', image_position VARCHAR(50) DEFAULT 'top-right',
    FOREIGN KEY (appointment_id) REFERENCES appointments(id),
    FOREIGN KEY (payment_id) REFERENCES payments(id),
    FOREIGN KEY (customer_id) REFERENCES customers(id)
);
CREATE TABLE loyalty_points (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    customer_id INTEGER NOT NULL,
    user_id INTEGER,
    points INTEGER DEFAULT 0,
    tier VARCHAR(20) DEFAULT 'bronze',
    total_points_earned INTEGER DEFAULT 0,
    total_points_redeemed INTEGER DEFAULT 0,
    points_earned INTEGER DEFAULT 0,
    points_redeemed INTEGER DEFAULT 0,
    transaction_type VARCHAR(20),
    transaction_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    expiry_date DATE,
    reference_id INTEGER,
    reference_type VARCHAR(50),
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customers(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE TABLE reviews (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    customer_id INTEGER NOT NULL,
    user_id INTEGER,
    appointment_id INTEGER,
    service_id INTEGER,
    stylist_id INTEGER,
    rating INTEGER NOT NULL,
    title VARCHAR(100),
    comment TEXT,
    service_rating INTEGER,
    stylist_rating INTEGER,
    value_rating INTEGER,
    ambiance_rating INTEGER,
    is_verified_purchase BOOLEAN DEFAULT 0,
    is_approved BOOLEAN DEFAULT 0,
    is_featured BOOLEAN DEFAULT 0,
    images JSON,
    reply TEXT,
    replied_at DATETIME,
    replied_by INTEGER,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customers(id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (appointment_id) REFERENCES appointments(id),
    FOREIGN KEY (service_id) REFERENCES services(id),
    FOREIGN KEY (stylist_id) REFERENCES stylists(id),
    FOREIGN KEY (replied_by) REFERENCES users(id)
);
CREATE TABLE notifications (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    appointment_id INTEGER,
    title VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    type VARCHAR(50),
    priority VARCHAR(20) DEFAULT 'normal',
    is_read BOOLEAN DEFAULT 0,
    read_at DATETIME,
    action_url VARCHAR(200),
    action_text VARCHAR(100),
    meta_data JSON,
    is_emailed BOOLEAN DEFAULT 0,
    emailed_at DATETIME,
    is_sms BOOLEAN DEFAULT 0,
    sms_sent_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (appointment_id) REFERENCES appointments(id)
);
CREATE TABLE products (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    sku VARCHAR(50) UNIQUE NOT NULL,
    barcode VARCHAR(50) UNIQUE,
    category_id INTEGER,
    supplier_id INTEGER,
    branch_id INTEGER,
    inventory_officer_id INTEGER,
    purchase_price FLOAT NOT NULL,
    selling_price FLOAT NOT NULL,
    wholesale_price FLOAT,
    quantity INTEGER DEFAULT 0,
    min_quantity INTEGER DEFAULT 0,
    max_quantity INTEGER,
    unit VARCHAR(20) DEFAULT 'piece',
    weight FLOAT,
    dimensions VARCHAR(50),
    images JSON,
    is_active BOOLEAN DEFAULT 1,
    is_featured BOOLEAN DEFAULT 0,
    is_taxable BOOLEAN DEFAULT 1,
    tax_rate FLOAT DEFAULT 0.0,
    expiry_date DATE,
    batch_number VARCHAR(50),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, image_url TEXT,
    FOREIGN KEY (category_id) REFERENCES categories(id),
    FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
    FOREIGN KEY (branch_id) REFERENCES branches(id),
    FOREIGN KEY (inventory_officer_id) REFERENCES inventories(id)
);
CREATE TABLE product_promotions (
    product_id INTEGER,
    promotion_id INTEGER,
    PRIMARY KEY (product_id, promotion_id),
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    FOREIGN KEY (promotion_id) REFERENCES promotions(id) ON DELETE CASCADE
);
CREATE TABLE suppliers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT NULL,
    contact_person VARCHAR(100),
    email VARCHAR(120),
    phone VARCHAR(20) NOT NULL,
    alternative_phone VARCHAR(20),
    address VARCHAR(200),
    city VARCHAR(50),
    state VARCHAR(50),
    country VARCHAR(50),
    postal_code VARCHAR(20),
    tax_id VARCHAR(50),
    registration_number VARCHAR(50),
    payment_terms VARCHAR(100),
    credit_limit FLOAT,
    balance FLOAT DEFAULT 0.0,
    categories_supplied JSON,
    is_active BOOLEAN DEFAULT 1,
    is_preferred BOOLEAN DEFAULT 0,
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE purchases (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id INTEGER NOT NULL,
    supplier_id INTEGER NOT NULL,
    inventory_officer_id INTEGER,
    purchase_order_number VARCHAR(50) UNIQUE,
    invoice_number VARCHAR(50),
    quantity INTEGER NOT NULL,
    unit_price FLOAT NOT NULL,
    total_price FLOAT NOT NULL,
    tax FLOAT DEFAULT 0.0,
    discount FLOAT DEFAULT 0.0,
    shipping_cost FLOAT DEFAULT 0.0,
    final_total FLOAT NOT NULL,
    purchase_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    delivery_date DATETIME,
    payment_status VARCHAR(20) DEFAULT 'pending',
    notes TEXT,
    is_received BOOLEAN DEFAULT 0,
    received_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (product_id) REFERENCES products(id),
    FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
    FOREIGN KEY (inventory_officer_id) REFERENCES inventories(id)
);
CREATE TABLE stock_movements (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id INTEGER NOT NULL,
    branch_id INTEGER NOT NULL,
    inventory_officer_id INTEGER,
    movement_type VARCHAR(20) NOT NULL,
    quantity INTEGER NOT NULL,
    previous_quantity INTEGER,
    new_quantity INTEGER,
    reference_type VARCHAR(50),
    reference_id INTEGER,
    reason VARCHAR(200),
    notes TEXT,
    movement_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (product_id) REFERENCES products(id),
    FOREIGN KEY (branch_id) REFERENCES branches(id),
    FOREIGN KEY (inventory_officer_id) REFERENCES inventories(id)
);
CREATE TABLE expenses (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    finance_id INTEGER,
    branch_id INTEGER,
    category VARCHAR(50) NOT NULL,
    description VARCHAR(200) NOT NULL,
    amount FLOAT NOT NULL,
    expense_date DATE NOT NULL,
    payment_method VARCHAR(50),
    receipt_number VARCHAR(50),
    is_approved BOOLEAN DEFAULT 0,
    approved_at DATETIME,
    approved_by INTEGER,
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (finance_id) REFERENCES finances(id),
    FOREIGN KEY (branch_id) REFERENCES branches(id),
    FOREIGN KEY (approved_by) REFERENCES users(id)
);
CREATE TABLE payrolls (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    finance_id INTEGER,
    employee_id INTEGER NOT NULL,
    employee_type VARCHAR(20),
    pay_period_start DATE NOT NULL,
    pay_period_end DATE NOT NULL,
    base_salary FLOAT NOT NULL,
    overtime_hours FLOAT DEFAULT 0.0,
    overtime_rate FLOAT DEFAULT 0.0,
    overtime_pay FLOAT DEFAULT 0.0,
    bonus FLOAT DEFAULT 0.0,
    commission FLOAT DEFAULT 0.0,
    allowance FLOAT DEFAULT 0.0,
    deductions FLOAT DEFAULT 0.0,
    tax FLOAT DEFAULT 0.0,
    insurance FLOAT DEFAULT 0.0,
    pension FLOAT DEFAULT 0.0,
    net_pay FLOAT NOT NULL,
    payment_date DATE,
    payment_status VARCHAR(20) DEFAULT 'pending',
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (finance_id) REFERENCES finances(id),
    FOREIGN KEY (employee_id) REFERENCES users(id)
);
CREATE TABLE commissions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    stylist_id INTEGER NOT NULL,
    appointment_id INTEGER,
    finance_id INTEGER,
    service_amount FLOAT NOT NULL,
    commission_rate FLOAT NOT NULL,
    commission_amount FLOAT NOT NULL,
    period VARCHAR(20),
    period_start DATE,
    period_end DATE,
    is_paid BOOLEAN DEFAULT 0,
    paid_at DATETIME,
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (stylist_id) REFERENCES stylists(id),
    FOREIGN KEY (appointment_id) REFERENCES appointments(id),
    FOREIGN KEY (finance_id) REFERENCES finances(id)
);
CREATE TABLE attendances (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    stylist_id INTEGER NOT NULL,
    branch_id INTEGER,
    date DATE NOT NULL,
    check_in_time DATETIME,
    check_out_time DATETIME,
    status VARCHAR(20) DEFAULT 'present',
    late_minutes INTEGER DEFAULT 0,
    early_leave_minutes INTEGER DEFAULT 0,
    overtime_minutes INTEGER DEFAULT 0,
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (stylist_id) REFERENCES stylists(id),
    FOREIGN KEY (branch_id) REFERENCES branches(id)
);
CREATE TABLE leave_requests (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    stylist_id INTEGER NOT NULL,
    branch_id INTEGER,
    leave_type VARCHAR(20) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason TEXT,
    status VARCHAR(20) DEFAULT 'pending',
    approved_at DATETIME,
    approved_by INTEGER,
    rejection_reason TEXT,
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (stylist_id) REFERENCES stylists(id),
    FOREIGN KEY (branch_id) REFERENCES branches(id),
    FOREIGN KEY (approved_by) REFERENCES users(id)
);
CREATE TABLE reports (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    branch_id INTEGER,
    generated_by INTEGER,
    report_type VARCHAR(50) NOT NULL,
    report_name VARCHAR(100) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    parameters JSON,
    data JSON,
    summary JSON,
    file_path VARCHAR(200),
    file_format VARCHAR(20),
    is_exported BOOLEAN DEFAULT 0,
    exported_at DATETIME,
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (branch_id) REFERENCES branches(id),
    FOREIGN KEY (generated_by) REFERENCES users(id)
);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_role_id ON users(role_id);
CREATE INDEX idx_appointments_customer_id ON appointments(customer_id);
CREATE INDEX idx_appointments_stylist_id ON appointments(stylist_id);
CREATE INDEX idx_appointments_branch_id ON appointments(branch_id);
CREATE INDEX idx_appointments_date ON appointments(appointment_date);
CREATE INDEX idx_appointments_status ON appointments(status);
CREATE INDEX idx_payments_customer_id ON payments(customer_id);
CREATE INDEX idx_payments_appointment_id ON payments(appointment_id);
CREATE INDEX idx_payments_status ON payments(payment_status);
CREATE INDEX idx_products_sku ON products(sku);
CREATE INDEX idx_products_barcode ON products(barcode);
CREATE INDEX idx_products_category_id ON products(category_id);
CREATE INDEX idx_stock_movements_product_id ON stock_movements(product_id);
CREATE INDEX idx_stock_movements_branch_id ON stock_movements(branch_id);
CREATE INDEX idx_notifications_user_id ON notifications(user_id);
CREATE INDEX idx_notifications_read ON notifications(is_read);
CREATE INDEX idx_reviews_service_id ON reviews(service_id);
CREATE INDEX idx_reviews_stylist_id ON reviews(stylist_id);
CREATE INDEX idx_reviews_customer_id ON reviews(customer_id);
CREATE TABLE prices (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    service_id INTEGER NOT NULL,
    price_type VARCHAR(20) DEFAULT 'regular', -- regular, promotional, seasonal, vip
    base_price DECIMAL(10,2) NOT NULL,
    current_price DECIMAL(10,2) NOT NULL,
    discount_percentage DECIMAL(5,2) DEFAULT 0.0,
    discount_amount DECIMAL(10,2) DEFAULT 0.0,
    tax_rate DECIMAL(5,2) DEFAULT 0.0,
    tax_amount DECIMAL(10,2) DEFAULT 0.0,
    final_price DECIMAL(10,2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'KES',
    is_active BOOLEAN DEFAULT 1,
    start_date DATETIME,
    end_date DATETIME,
    reason VARCHAR(255),
    created_by INTEGER,
    updated_by INTEGER,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id)
);
CREATE TABLE price_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    service_id INTEGER NOT NULL,
    old_price DECIMAL(10,2),
    new_price DECIMAL(10,2),
    old_discount DECIMAL(5,2),
    new_discount DECIMAL(5,2),
    reason VARCHAR(255),
    changed_by INTEGER,
    changed_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (service_id) REFERENCES services(id),
    FOREIGN KEY (changed_by) REFERENCES users(id)
);
CREATE INDEX idx_reviews_user_id ON reviews(user_id);
CREATE TABLE appointment_services (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    appointment_id INTEGER NOT NULL,
    service_id INTEGER NOT NULL,
    price FLOAT NOT NULL DEFAULT 0.0,
    duration INTEGER DEFAULT 30,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (appointment_id) REFERENCES appointments(id) ON DELETE CASCADE,
    FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE CASCADE
);
CREATE INDEX idx_appointment_services_appointment ON appointment_services(appointment_id);
CREATE INDEX idx_appointment_services_service ON appointment_services(service_id);
