services:
  - type: web
    name: urban-chic-backend
    env: python
    rootDir: backend
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn -w 4 -b 0.0.0.0:10000 vercel_app:app
    envVars:
      - key: DATABASE_URL
        value: mysql+pymysql://root:zakariadowiman@acela.proxy.rlwy.net:57015/railway
      - key: SECRET_KEY
        value: b5317a7e127ad46718481c981788777351a639670e0fe715becf0f0682ef0046
      - key: FLASK_ENV
        value: production
      - key: FRONTEND_URL
        value: https://urban-chic-frontend.vercel.app
      - key: CORS_ORIGINS
        value: https://urban-chic-frontend.vercel.app,http://localhost:5173,http://localhost:3000
      - key: RENDER
        value: true
      - key: PYTHONPATH
        value: backend
      - key: MAIL_USERNAME
        value: zakariaadow191@gmail.com
      - key: MAIL_PASSWORD
        value: xwjafqpehjpwvxoj
      - key: MAIL_DEFAULT_SENDER
        value: zakariaadow191@gmail.com
      - key: DB_POOL_SIZE
        value: 5
      - key: DB_MAX_OVERFLOW
        value: 2
      - key: DB_POOL_RECYCLE
        value: 280